// Washington peaks for the header. One is picked at random on every visit.
//
// Each scene is generated from real elevation data (AWS Terrain Tiles, see public/third-party-licenses.txt):
// the view from a lookout some kilometres away, facing `look`, with the peak right of centre and the
// ranges around it. To regenerate or tune a view, see tools/skyline.py and tools/peaks.json.
// Characters (shadowed / sunlit): '#'/'h' near foothills, '%'/'m' the peak's own range, '=' ranges beyond,
// 's'/'*' snow, '+' distant snow. Heights are kept close to true (at most 1.3x), so small peaks stay small.

export type Peak = {
  name: string
  lat: number // degrees north
  lon: number // degrees west
  metres: number
  feet: string
  look: 'north' | 'south' // which way the viewer faces; the sky behind the peak matches
  grid: string[]
}

export const peaks: Peak[] = [
  {
    name: 'Mt. Baker',
    lat: 48.7768,
    lon: 121.8145,
    metres: 3286,
    feet: '10,781',
    look: 'north',
    grid: [
      '..................................................................................................................................**sssss',
      '................................................................................................................................*****sssss',
      '................................................................................................................................*****ssssss',
      '...............................................................................................................................**********ss',
      '..............................................................................................................................************ss',
      '...........................................................................................................................***************ssss',
      '................................................................................................................m.........*****************ssss',
      '..............................................................................................................mmmmmmm...*******************sssss',
      '..................................................................................................%%.........mmmmmmmm**********************sssssss',
      '.................................................................................................*%%......*.mmmmmmmmm***********************ssssssss',
      '................................................................................................**%%.....*mmmmmmmmmm*****************ssss***sssssssss',
      '...............................................................................................*ss%%%%%mmmmmmmmmmmm*****************ssssss*sssssssssss',
      '............................................................................................mmm*ss%%%%%mmmmmmmmm********************ssssssssssssssssssss',
      '............................................................................................mmmmm%%%%%%mmmmmmmm*********************sssss**ssssssssssssss',
      '...........................................................................................mmmmmm%%%%%%%****mm****mm*****************sss%%*ssssssssssssssss',
      '.........................................................................................mmmmmmmmm%%%%%*****m****mmmm*****************s%%%%ssssssssssssssssss',
      '.....................................................................................s...mmmmmmmmmm%%%*****mmm**mmmmm*****************%%%%%%ssssssssssss**sss%%',
      '...................................................................................***s.mmmmmmmmmmmm%*****mmmmmmmmmmmm***********mmmmmm%%%%%%s***ssssss%%%%s%%%%%',
      '..............................................................................**.*****mmmmmmmmmmmmmm%%***mmmmmmmmmmmmmmmmmm****mmmmmmmmm%%%%%%%%%***ss%%%%%%%%%%%%%%',
      '.........................................................................mm%%%*******mmmmmmmmmmmmmmm%%%%%mmmmmmmmmmmmmmmmmmm**mmmmmmmmmm%%%%%%%%%%***%%%%%%%%%%%%%%%%%',
      '.......................................................................mmmmm%%%***mmmmmmmmmmmmmmmmmm%%%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%%%%%**m%%%%%%%%%%%%%%%%%%...%%%%%.........................==.......++',
      '.................................................................mmmmmmmmmmmm%%%mmmmmmmmmmmmmmmmmmmm%%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%%%mmm%%%%%%%%%%%%%%%%%%%%%%%%%mmm%%%.=======...=......====..=.==+++.=+++=',
      '.............................................................mmmmmmmmmmmmmmmmm%%mmmm##mmmmmmmmmmmmmmm%%mmmmmmmmmmmmmmmmmmmmmmmmmmmm%mmmmmmmmm%%%%%%%%mmmm%%%%%%%%%%%%%%%%%%%%%%mmmmmmmm=======m%%%....m============++=======',
      '......................................................mmmmmmmmmmmm%mmmmmmmmmmm%%mm########mm######mmmmmmmmmmm%%mmmmmmmmmmmmmmmmmmmm%%mmmmmmmmm%%%%%%%mmmm%%%%%%%%%m%%%%%%%%%%%%mmmmmmmmmmmmm=mmm%%%%mmmm====================',
      '................%%%.%%.%............................mmmmmmmmmmmmmm%%mmmmmmmmmm%%m###################mmmmmmm%%%%%%mmmmmmmmmmmmmmmmmm%%%mmmmmmmm%%%%%%%#####%%%%%%%mmm%%%%%%%%%%%%mmmmmmmmmmmmmmmmm%%%mmmm%%mmmm==============',
      '...............%%%%%%%%%%%%..m..................m%%mmmmmmmmmmmmmmhhhhhhmmmmmmhhhh#######################mmm%%%%%%%mmmmmmmmmmmmmmmmm%%%%mmmmmmm%%%%hhh######%%%%%#mmm%%%%%%%%%%%%%%mmmmmmmmmmmmmmmm%%mmmm%%%mmmmmmmmm========',
      'mm..mmmm%%%%..%%%%%%%%%%%%%%mmm%%.m.......m.mmmmmmmmm%%%mmmmmm%%hhhhhhhhhhhhhhhhhh#######################m%%mm%%%%%mmmmmmmmmmmmmmmm%%%%%mmmmmm%%%hhhh##hh##hhh#####hhh###%%%%%%%%%%mmmmmmmmmmmmmmm%%%mm%%%%%mmmmmmmmmmm=====',
      'mmmmmmmmm%%%%%%%%%%%%%%%%%%%mmmm%%mmm.mmmmmmmmmmmmmm%%%%%mmmm%%%hhhhhhhhhhhhhhhhhhhhhh###########h######hh###m#%%%%%mmmmmmmmmm####%%%%%%mmmmmm%%hhhhh#hhhhhhhhh####hhh####%%%%%%%%%%mmmmmmmmmmmmmmm%%%%%%%%%mmmmmmmmmmmmmm==',
      'mmmmmmmmmhh##%%%%%%%%%%%%%%%mmmmm%mmm%%mmmmmmmmmmmmm%%%%%mmmm%###hhhhhhhhhhhhhhhhhhhhh##########hhhh###hhhh#####%%%######hhhhh#####%%%%%mmmmhhhhhhhhhhhhhhhhhhhh###hhh######%%%%%%%%%%%mmmmmmmmmmmm%%%%%%%mmmmmmmmmmmmmmmmmm',
      'mmhhhhhhhhh###%%%%%%%%%%%%%%mmmmmmmmm%%%%%mmmmmmmmmm%%%%mmmmhh####hhhhh#######hhhh##############hhhhh###hhhh#########hhhhhhhh#######%%%mmmmhhhhhhhhhhh##hhhhhhhh####h########%%%%%%%%%%%mmmmmmmmmmm%%%%%%%mmmmmmmmmmmmmmmmmm',
      '#hhhhhhhhhhh###%%%%%%%%%%%%mmmmmmmmmm%%%%%%mmmmmmmm%%%%mmmmhhhhh################################hhhhh###hhhh######hhhhhhhhhhh###########mmhhhhhhhhhhhh####hhhhhh###################%%%%%mmmmmmmmmmmm%%%%%mmmmmmmmmmmmmmmmmmm',
      '##hhhhhhhhhhh####%%%%%%%%%mmmmmmmmmm%%%%%%%mmmmmm%%%%%mmhhhhhhhhh###############################hhhhh####hh######hhhhhhhhhhhh############hhhhhhhhhhhh######hhhhh######################%hhh###mmmmmmmm%%%mmmmm%%%mmmmmmmmmmmm',
      '###hhhhhhhhhhh#######%%%%%mmmmmmm####%%%%%####mmm%%%hhhhhhhhhhhhh###############################hhhhhh##hh######hhhhhhhhhhhhhhhhhhh#######hhhhhhhhhhh########hhh#######################hhhh###mmmmmmm%%mmmmmm%%mmmmmmmmmmmmm',
      '####hhhhhhhhhh########%%%%mmmmm#######hhhh########hhhhhhhhhhhhhhh###############################hhhhhhhhhhh####hhhhhhhhhhhhhhhhhhhhhh########hhhhhhh####################################hhhhhhhhh######mmmmmmmmmmmmmmmmmmmmm',
      '#####hhhhhhhhh#########%%%mmmm########hhh#########hhhhhhhhhhhhhh#################################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh####################################################hhhhhhhh######mmmmmmmmmmmmmmmmmmmm',
      '########hhhhhh#####################################hhhhhhhhh#######################################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh#######################################################hhhhh##########mmmmmmmmmmmmmmm',
      '#########hhhhh#######################################################################################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh########################################################hhhhhhhhh############hh##mmmm',
      '#########hhhhhhhhhhhhh################################################################################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh######hhh######################################hhh#####hhhhhhhhhhh##########hhh###mm',
      '########hhhhhhhhhhhhhh################################################################################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh######hhhh####################################hhhhh#####hh##hhhhhhh##########hh#####',
      '############################################################################################################################################################################################################################',
    ],
  },
  {
    name: 'Mt. Rainier',
    lat: 46.8529,
    lon: 121.7604,
    metres: 4392,
    feet: '14,411',
    look: 'north',
    grid: [
      '.................................................................................................................................*s..**sss',
      '................................................................................................................................**ssssssssssss',
      '..............................................................................................................................***mmsssssssssssss',
      '............................................................................................................................****mmmmsssssssssssss',
      '........................................................................................................................******mmmmmm*****ssssssssss',
      '.......................................................................................................................****m***mmmmm******ssssssssss',
      '...................................................................................................................mmmm*mmmmmm*mmmmm******ssssssssss',
      '...................................................................................................................mmmmmmmmmm***mmm*******sssssssss*ss',
      '..................................................................................................................mmmmmmmmmm****%*********msssssss**smmm%%',
      '................................................................................................................mmmmmmmmmmmm***%%**m*****mmmssssss%mmmmm%%',
      '...............................................................................................................mmmmmmmmmmmm****%%*mmm****mmmsssss%%mmmmmm%s',
      '............................................................................................................***mmmmmmmmmmm*****%%mmm****mmmmmsss%%%%mmmmmmss',
      '...........................................................................................................****mmmmmmmmm******%%%mm*****smmmmms%%%%%mmmmmmsss',
      '..........................................................................................................*****mmmmmmmm*******%%%******ssmmmmmm%%%%%smmmm**ssss*m',
      '.........................................................................................................******mmmmmmmmm******%%*******sssmmmmm%%%%sssmm****sssssss',
      '........................................................................................................******mmmmmmmmmm***************sssmmmmmm%%sssss******sssssss.%..........smms',
      '......................................................................................................*******mmmmmm%%%*****************ssssmmmmmmmssss********sssss****.........mmmms',
      '......................................................................................................*******mmmmm%%%%******************ssssmmmmmmssss*********s********s.....m.mmmmms',
      '....................................................................................................*********mmmmm%%%******m************sssss***mmssss******************sssssmmmmmmmmms',
      '...................................................................................................***********mmmm%%*******m*************sssss***msss******************ssssssmmmmmmmmmmss',
      '.................................................................................................*************m*m**************************ssss***sss******************sssssssmmmmmmmmmmsss',
      '................................................................................................*************%******************************ssss**sss******************sssssssssmmmmmmmmmmmsss........**',
      '..............................................................................................***************%******************************ssssssssss******************ssssssssssmmmmmmmmmmsss.sss..*****',
      '......................................................................................*..***m***********************************************ssssssssss*******************ssssssssssssmmmmmm***sssss********',
      '....................................................................................*******mmm********************%********************mmm***ssssssssss*******mmm***********sss%%ssssmmmm*****msssss*******mmm',
      '.................................................................................*********mmmmmmmmm****ss******mm%%%m*************mmmmmmmmm**sssssssssssmm**mmmmmmm**********s%%%%%smmmmm****mmmmsss*%%%%%%mmmmss',
      '..............................................................................**********mmmmmmmmmmmm**ss**mmmmmmm%%%mmmmmmm******mmmmmmmmmmmm%%%%sssssssmmmmmmmmmmmm*********m%%%%%%%mmmm****mmmmmmm%%%%%%%mmmmss***m',
      '...........................................................................mmm******mmmmmmmmmmmmmmmmmmmm*mmmmmmmmm%mmmmmmmmm****mmmmmmmmmmmmm%%%%%%ssss%mmmmmmmmmmmmmmmmmmmmmmm%%%%%%%%%%%%**mmmmmmmm%%%%%mmmmmmmm*mmmm',
      '................................................................%......m%%mmmmm****mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%ss%%mmmmmmmmmmmmmmmmmmmmmmm%%%%%%%%%%%%%mmmmmmmmmm%%%%mmmmmmmmmmmmmm%%',
      '..............................................................mm%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%%%%mmmmmmmmmmmmmmmmmmmmmmm%%%%%%%%%%%%%mmmmmmmmmm%%%mmmmmmmmmmmmmmmm%%%',
      '.............................................................mmm%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%%mmmmmmmmmmmmmmmmmmmmmmm%%%%%%%%%%%%mmmmmmmmmmm%%%%mmmmmmmmmmmmmmmmmm',
      '...........................................................mmmm%%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%%mmmmmmmmmmmmmmmmmm%mmmm%%%%%%%%%mmmmmmmmmmmmm%%%%mmmmmmmmmmmmmmmmmm',
      '.................................................m.mmmmm%%mmmm%%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%mmmmmmmmmmmmmmmmmmmmmmmmmm%%mmmmmm%%%%%%mmmmmmmmmmmmmmmmm%%%mmm%%%%%%%%mmmmmmmmmmmmm%%%%%%mmmmmmmmmmmmmhh##',
      '...............................................mmmmmmmmm%%mmm%%%%mmmmmmmmmmmmmmmmmmm%mmmmmmmmmmmmmmmmmmmmmmm%%%%%mmmmmmmmmmmmmmmmmmmmmmmmm%%%%mmmmmm%%%%%mmmmmmmmmmmmmmmmmm%mmmmm%%%%%%%mmmmmmmmmmmmmm%%%%%%mmmmmmmmmmmhhhh#',
      '..........................................mm%%mmmmmmmmm%%%%mm%%%%mmmmmmmmmmmmmmmmmm%%%%mmmmmmmmmmmmmmm%%%mmmm%%%%mmmmmmmmmmmmmmmmmmmmmmmmm%%%%%mmmm%%%%%%mmmmmmmmmmmmmmmmmmmmmmmmmm%%%%##mmmmmmmmmmmmmhhhhhh%mmmmmmmmmhhhhhh',
      '.......................................mmmmm%%%mmmmmmm%%%%%mm%%%%mmmmmmmmmmmmmmmmmm%%%%%mmmmmmmmmmmmm%%%%%mmmm%%%%mmmmmmmmmmmm##mmmmmmmmmm%%%%%%mm%%%%%%%mmmmmmmmmmhhhm%%%mmhhhhmmhhhh#########mmmmmmhhhhhhhhhmmmmmmhhhhhhhh',
      '.................................mm%%%%%mmm%%%%%mmmmm%%%%%mmmm%%%%%%mmmmmmmmmmmmmmm%%%%mmmmmmmmmmmmm%%%%%%mmmmm%%%%%mmmmmmmmm########mmmmm%%%%%%%%%%%%%%%mmmmmmmmmhhhhh%%%%hhhhhhhhhhhh#########hhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      '.............................mmmmmmm%%%%%%%%%%%%%mmmm%%mmmmmmm%%%%%%%mmmmmmmmmmmmm%%%%%mmmmmmmmmmmmm%%%%%mmmmmm%%%%%mmmmmmhhhh########mmm#%%%%%%%##%%%%%mmmmmmm##hhhhhh####hhhhhhhhhhhhh#######hhhhhhhhhhhhhhhhhhhhhhhhh##hh',
      '...........mmmm%%%%%%%%%%%%%%mmmmmmm%%%%%%%%%%%%%mmmmmmmmmmmmm%%%%%%%%%mmmmmmmmmm%%%%%mmmmm%%%mmmmmm%%%%%mmhhhhh%%hhmmmmhhhhhhhhhh####h###%%%%%hh####%%mmmmmhhh##hhhhhh#####hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh####h',
      '############################################################################################################################################################################################################################',
    ],
  },
  {
    name: 'Mt. Adams',
    lat: 46.2025,
    lon: 121.4908,
    metres: 3743,
    feet: '12,281',
    look: 'north',
    grid: [
      '...................................................................................................................................*.****',
      '..............................................................................................................................mm.**********',
      '............................................................................................................................**mm***********ss',
      '............................................................................................................................****************sss',
      '...........................................................................................................................******************ss',
      '.........................................................................................................................********************sssss',
      '.........................................................................................................................********************sssss',
      '........................................................................................................................**********************sssss',
      '......................................................................................................................***************************ss',
      '.....................................................................................................................******************************ss',
      '....................................................................................................................*******************************ssss',
      '...................................................................................................................********************************ssssss',
      '.................................................................................................................**********************************ssssssss',
      '..............................................................................................................**************************mm**********ssssssss%',
      '............................................................................................................*****mm********************mmmm*********sssssss%%%',
      '...........................................................................................................*****mmmmm************mmmmmmmmmmm********sssss%%%%%%%%',
      '.........................................................................................................mmmm**mmmmmmmmmmmm*****mmmmmmmmmmmmmmmmmmm**s%%%%%%%%%%%%%mm',
      '........................................................................................................mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%%%%%%%%%%%%%%%mm%%%',
      '.....................................................................................................mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%%%%%%%%%%%%%%%%mm%%%',
      '...................................................................................................mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%mm%%%%%%%%%%%%%%mmm%%',
      '.................................................................................................mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%%%%%%%%%%%%%%%mmmm%',
      '.............................................................................................mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%%%%%%%%%%%%%%%mmm%%',
      '..........................................................................................mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%%%%%%%%%%%%%%%%%%%%%m.%%.....mm%%',
      '.......................................................................................mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%m%%%%%%%%%%%%%%%%%%%%%%%%%%%%mm%%%%%%%m%%%%%%%%',
      '...............................................................................m%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%mmmmm%%%%mmm',
      '..........................................................................mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%mmmmmm%%mmmm%',
      '.......................................................................mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%%%%%%%%%%mmm%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%mmmmmmmmmmmmm%%%',
      '...............................................................%%%%%mmmmmmmmmmmmmmmmmmmmmmm%%%%%%%%%%%%%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%mmmmm%%%%%%%%mm%%%%mmmm%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%mmmmmmmmmmm%%%%%%%',
      '.........................................................mmmmm%%%%%mmmmmmmmmmmmmmmmmm%%%%%%%%%%%%%%%%%%%%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%mmmmmmm%%%%%mm%%%%mmmmmmm%%%%%%mmmmm%%%%%%%%%%%%%%%%%%%%mmmmmmm%%%%%%%%%%%',
      '.....................................=...........%%%%%%%mmmmm%%%m%%mmmmmmmmmmmmmmmmm%%%%%%%%%%%%%%%%%%%%%%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%mmmmmmmm%%%%%%%%%%mmmmmmmmm%%%%mmmmmmmm%%%%%%%%%%%%%%%%%%%%%%%%%%%mmm%%%%%',
      '...................====............======mmmmmmm%%%%%%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%%%%%%%%%%%mmm%%%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%%mmmmmmm%%%%%%%%%%mmmmmmmm###%%#mmmmmmmhhhhhh%%%%%%%%%%%%%%%%%%%%mmmmm%%mm',
      '=====..=.============================mmmmmmmmmmm%%%%%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%%%%%%%%%%%mmmmmm%%mmm%%%%%%mmmmmmmmmmmmmmmmmmmmmm##%%%%%%hh###########%%%hhhhhhhhhhh###########hhhhhhhhhh###%%%###%%%%%%%%##mmmmmmm',
      '================================mmmmmmmmmm%%%%%%%%%%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%%%%%%%%%%%%mmmmmmmmm%%%%%%%%mmmmmmmmhhhhhhhhhhhh######hhhhh#############hhhhhhhhhhhhh##########hhhhhhhhhhh#########################',
      'mmmm%%====================mmmmmmmmmmmmm%%%%%%%%%%%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%%%%%%%m%%%%%%%%mmmmm#%%%%%%%%hhhhhhhhhhhhhhhhhhhh####hhhhhhh############hhhhhhhhhhhhh###########hhhhhhhhhhhhhhhh###################',
      'mmm%%%%mmmm%%%========mmmmmmmmmmmm%%%%%%%%%%%%%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm#%%%%%%%%%%%mmm%%%%%%%%############hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh############hhhhhhh####hh###########hhhhhhhhhhhhhhhhhhh###############',
      'mm%%%%%mmmm%%%%mmmmmmmmmmmmm%%%%%%%%%%%%%%%%%mmmmmmmmmmmmmmmmmmmmmmmhhhhh###########%%%%%%%%%mmmm%%%%%%%#############hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh###########hhhhhh#####hhhh#############hhhhhhhhhhhhhhhhh#############',
      'm%%%%%%%%m%%%%%mmmmmmmm%%%%%%%%%%%%%%%%%%%%mmmmmmhhhmmmmm###hhhhhhhhhhhhh#############%%%%%hhh#######################hhhhhhhhhhhhh###hhhhhhhhhhhhhhhhhhh########hhhhhhh####hhhhhhh################hhhhhhhhhhhhhhh###########',
      '%%%%mm%%%%%%%%mmmmmmm%%%%%%%%%%%%%%%%%%#hhhh####hhhhhhhh####hhhhhhhhhhhh###############%%%#hh########################hhhhhhhhhhhh#####hhhhhhhhhhh#hhhhhhhhh###hhhhhhhhh#hhhhhhhhhh####################hhhhhhhhhhhhhh########',
      '%%%%mm%%%%%%%mmmm%%%%%%%%%%%%%%%%hhhhh###hhh####hhhhhhh######hhhhhhhh################################################hhhhhhhhhhhh######hhhhhhhhh#####hhhhhhhhhhhhhhhhhhhhhhhhhhhhh#######hhhhh##########hhhhhhhhhhhhh#######',
      '############################################################################################################################################################################################################################',
    ],
  },
  {
    name: 'Mt. St. Helens',
    lat: 46.1912,
    lon: 122.1944,
    metres: 2549,
    feet: '8,363',
    look: 'south',
    grid: [
      '.........................................................................................................................................%%%',
      '...........................................................................................................******......%%........%%mmmm.%%%%%%%%s',
      '..........................................................................................................********..m.%%%%.....%%%%mmmm%%%%%%%%%ssss*',
      '........................................................................................................%*******mmmmm*%%%mm*sss%%%%%mm%%%%%%%%%%sss***',
      '........................................................................................................mm****mmmmmmmmmmmmm**ss%%%%%%%%%%%%%%%%%ss******',
      '......................................................................................................ssmmmmmmmmmmmmmmmmmmmm**s%%%%%%%%%%%%%%%%sss******m',
      '.....................................................................................................sssmmmmmmmmmmmmmmmmmmmmmsss%%%%%%%%%%%%%%ssss******mmm',
      '...................................................................................................%sss%%mmmmmmmmmmmmmmmmmmmmsss%%%%%%%%%%%%%%sssss****mmmmm',
      '..................................................................................................%%%ss%%%mmmmmmmmmmmmmmmmmmssss%%%%%%%%%%%%%%%ssssss*mmmmmmmm',
      '.................................................................................................%%%%%s%%%%mmmmmmmmmmmmmmmm%sss%%%%mm%%%%%%%%%%%%%%%%mmmmmmmmmmm',
      '...............................................................................................%%%%%%%%%%%%%mmmmmmmmmmmmmm%%%%%%%%%mmmm%%%%%%%%%%%%%%%mmmmmmmmmmmm',
      '.............................................................................................%%%%%%%%%%%%%%%%mmmmmmmmmmmm%%%%%%%%%%mmmmm%%%%%%%%%%%%%%mmmmmmmmmmmmmmm.m',
      '............................................................................................%%%%%%%%%%%%%%%%%mmmmmmmmmmmm%%%%%%%%%%%mmm%%%%%%%%%%%%%%%mmmmmmmmmmmmmmmmmmm',
      '...........................................................................................%%%%%%%%%%%%%%%%%%mmmmmmmmmmmmm%%%%%%%%%%%%%%%%%%%%%%%%%%%%mmmmmmmmmmmmmmmmmmmm',
      '..........................................................................................%%%%%%%%%%%%%%%%%%mmmmmmmmmmmmmmm%%%%%%%%%%%%%%%%%%%%%%%%%%mmmmmmmmmmmmmmmmmmmmmmm',
      '........................................................................................%%%%%%%%%%%%%%%%%%%%mmmmmmmmmmmmmmm%%%%%%%%%%%%%%%%%%%%%%%%%%mmmmmmmmmmmmmmmmmmmmmmmm',
      '......................................................................................%%%%%%%%%%%%%%%%%%%%%mmmmmmmmmmmmmmmm%%%%%%%%%%%%%%%%%%%%%%%%%%mmmmmmmmmmmmmmmmmmmmmmmmm',
      '....................................................................................%%%%%%%%%%%%%%%%%%%%%%%mmmmmmmmmmmmmmm%%%%%%%%%%%%%%%%%%%%%%%%%%mmmmmmmmmmmmmmmmmmmmmmmmmmm',
      '..................................................................................%%%%%%%%%%%%%%%%%%%%%%%%%mmmmmmmmmmmmmm%%%%%%%%%%%%%%%%%%%%%%%%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmmm',
      '.................................................................................%%%%%%%%%%%%%%%%%%%%%%%%%%mmmmmmmmmmmmmm%%%%%%%%%%%%%%%%%%%%%%%%%mmmmmmmmmmmmmmmmmmmmmmmmm%mmmmmm',
      '................................................................................%%%%%%%%%%%%%%%%%%%%%%%%%%%mmmmmmmmmmmmmm%%%%%%%%%%%%%%%%%%%%%%%%mmmmmmmmmmmmmmmmmmmmmmmmmm%mmmmmmmm',
      '............................................................................##%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%mmmmmmmmmmmm%%%%%%%%%%%%%%%%%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm',
      '..........................................................................######%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%mmm%%%%%%%%%%%%%%%%%%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%mmmmmmmm',
      '.................................................................%%%%%#.#########%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%m%%%%%%%%%%%%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%mmmmmmmmmm',
      '====......==========..=..==......=...........%%..............#..%%%%%##############%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%mm%%%%%%%%%%%%%%mmmmmmmmmmmmmmmmmmmm%%mmmmmmmmmmmmmmm%%%%%mmmmmmmmmmm',
      '=========================================...%%%m........########%%%#################hh%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%mm%%%%%%%%%%%%%%mmmmmmmmmmmmmmmmmmmm%%%%mmmmmmmmmmmmmm%%%%%mmmmmmmmmmmmmm',
      '=========================================%%%%%mmmm%%#=##############################hhh%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%mmm%%%%%%%%%%%%%%mmmmmmmmmmmmmmmmmmmmm%%%mmmmmmmmmmmmmmm%%%%%%%mmmmmmmmmmmmmmmm',
      '====================================hhhhhh%%%mmmm%%%#################################hhh%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%mmm%%%%%%%%%%%%%mmmmmmmmmmmmmm%mmmmmmm%%%%mmmmmmmmmmmmmmmm%%%%%%%%mmmmmmmmmm%%%mmm',
      '===============================####hhhhhhhhhmmmm%%%####################################hh%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%mmmm%%%%%%%%%%%%%mmmmmmmmmmmmmm%mmmmmm%%%%%%mmmmmmm%%%%%%mmmmm%%%%%%%%mmmmmmm%%mmmmmmm.............=',
      'hhhhhhhhhh====##=======mmm==#######hhhhhhhhhhmm###########################################%%%%%%%%%%%%%%%%%%%%%%%%%mmmmmmmm%%%%%%%%%%%%%%%mmmmmmmmmmmmmmmmmmm%%%%%%%%mmmmm%%%%%%%%%mmmm%%%%%%%%mmmmmm%%mmmmmmmm%%mmmmmm=====',
      'hhhhhhhhhhhhhhhhhhhh=###mmhh####hhhhhhhhhhhhh##############################################%%%%%%%%%%%%%##%%%%%%%%mmmmmmmmm%%%%%%%%%%%%%%%%mmmmmmmmmmmmmmm%%%%%%%%%%%%mmmm%%%%%%%%%%%mmm%%%%%%%%mmmmmmmmmm%%mm%%%mmmmmm%%%%%',
      'hhhhhhhhhhhhhhhhhhhh####hhhhh##hhhhhhhhhhh###################################################%%%%%##########%%%%%%mmmmmmmhh%%%%%%%%%%%%%%%%%mmmmmmmmmmm%%%%%%%%%%%%%%%%mmmm%%%%%%%%%%%%%%%%%%%%%%mmm#%%%%%%%%%%%%mmmmmm%%%%%',
      'hhhhhhhhhhhhhhhhhhhh####hhhhhhhhhhhhhhh############################################################################mm###hhhh%%%%%%%%%%%%%%%%%mmmmmmmmm%%%%%%%%%%%%%%%%%%mm%%%%m%%%%%%%%%%%%%%%%%%######%%%%%%%%%%%mmmmmm%%%%',
      'hhhhhhhhhhhhhhhhhhhh###hhhhhhhhhhhhhhh###################################################################################hhh%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%mmm%%%%%%%%%%%%%%%%##########h%%%%%%%%mmmmmm%%%',
      'hhhhhhhhhhhhhhhhhhh####hhhhhhhhhhhhh##########################################################################################%%%%#######%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#mm#%%%%########################%%%%%%##mmmmm%%',
      'hhhhhhhhhhhhhhhhhhh####hhhhhhhhhhhh#######################################################################################################hhhh###########%%%%%%%%%%%%########################################hhh#####hhhmm%%',
      'hhhhhhhhhhhhhhhhhhhh###hhhhhhhhhhh#######################################################################################################hhhhh############hhhh#################################################hh####hhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh#########################################################################################################hhhhh############hhhh########################################hh#######hhh##hhhhhhhh',
      'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh###########################################################################################################hhhh#############hhhhhh####################################hhhh#######h###hhhhhhhh',
      '############################################################################################################################################################################################################################',
    ],
  },
  {
    name: 'Glacier Peak',
    lat: 48.1125,
    lon: 121.1139,
    metres: 3213,
    feet: '10,541',
    look: 'north',
    grid: [
      '........................................................................................................................................*s',
      '.....................................................................................................................................****ss',
      '....................................................................................................................................*****ssss',
      '..................................................................................................................................*******ssssss',
      '.................................................................................................................................********sssssss',
      '..............................................................................................................................***********ssssssss........#.#',
      '............................................................................................................................**************sssssss**...hhh#########.....**',
      '...........................................................................................................................****************ssssshh****hhhh#############**##s##',
      '.............................#............................................................................................******************ssshhhh**hhhhhh#####################..................................ss',
      '...........................hhh##.........................................................................................*******************sshhhhhhhhhhhhhh######################hhhhhh##..............mmm......**ssss...hh',
      '.######....hhh###..###..###hhh#####............##.##...................................................................*****************#####hhhhhhhhhhhhhhhh#####hhh############hhhhhhhh###...........%mmmmm.mm.**sssshhhhh',
      'hh##########################h#######.....###############............................................................mmm**********hhhh#######hhhhhhhhhhhhhhhhhhhhhhhhhh###########hhhhhhhh#########....%mmmmmmmmm****shhhhhhh',
      'hh#####################hh###############################hh..............................mm%%......................mmmmmm*******hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh##########hhhhhhhhhh#########..###mmmmmmm***hhhhhhhhh',
      'hhh##################hhhh##############################hhh##...%%%%.................mmmmmm%%%hh#hh.............%%mmmmmmmm%*mmhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh##########hhhhhhhhhhh#############mmmmmmhhhhhhhhhhhh',
      'hhh#################hhhhh##############################hhh######%%%%%h..#%%mmmmmmmmmmmmmmm%%hhhhhhhhh#.....####%%mmmmmmm%%%mmhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh########hhhhhhhhhhhhh#############mmmhhhhhhhhhhhhh',
      'hh################hhhhhh###############################hhh#######%%%hhh####mm###mmmmmmmmmhhhhhhhhhhhh##########hhmmmmmmm%%%mhhhhhhhhhhhhhhhhhh##hhhhhhhhhhhhhhhhhhhhhhhhhhhh#####hhhhhhhhhhhhhhh############hhhhhhhhhhhhhhhh',
      'hh###############hhhhh###############################################h###########mmmmmmhhhhhhhhhhhhhhhh#######hhhh###mmmm%%hhhhhhhhhhhhhhhhhhh##hhhhhhhhhhhhhhhhhhhhhhhhhhhhhh#hhhhhhhhhhhhhhhhhhhh######hhhhhhhhhhhhhhhhhhh',
      'hh##############hhhh#############################################################hhhhhhhh######hhhhhhhhhhh##hhhhhhh##hhhhhhhhhhhhhhhhhhhhhhhhh##hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhh###########hhhhhh###################hhhhh##################################hhhhhhhhhh##########hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh###hhhhhhhhhhhhhhhhhhhh#hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhh#########hhhhhhhhh#################hhhhhhhh##############################hhhhhhhhh##############hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh###hhhhhhhhhhhhhhhhhhhh#hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hh#########hhhhhhhhhhh################hhhhhhhh###########################hhhhhh####################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh########hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hh##########hhhhhhhhhhh################hhhhhhhh#########################hhhhhh######################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh###########hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'h##############hhhhhhhhh################hhhhhhhh#####################hhhhhhhhh######################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh##hhh####hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      '###############hhhhhhhhhh################hhhhhhh####################hhhhhhhhhhh#####################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh###########hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      '###############hhhhhhhhhhh#################hhhhh####################hhhhhhhhhhh####################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh############hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      '###############hhhhhhhhhhh#########################################hhhhhhhhhhhh###################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh###############hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      '################hhhhhhhhhhh#######################################hhhhhhhhhhhhh##################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh####################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      '################hhhhhhhhhhh######################################hhhhhhhhhhhhhh#################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh#######################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      '#################hhhhhhhhhhh#####################################hhhhhhhhhhhhhhh###############hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh###########################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      '##################hhhhhhhhhh####################################hhhhhhhhhhhhhhhhh#############hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh##############################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      '####################hhhhhhhh###################################hhhhhhhhhhhhhhhhhhh############hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh##################################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      '#####################hhhhhhh##################################hhhhhhhhhhhhhhhhhhhh###########hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh######################################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      '######################hhhhhh#################################hhhhhhhhhhhhhhhhhhhhh###########hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh########hhhhhh#########################################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      '########################hhh################################hhhhhhhhhhhhhhhhhhhhhhhh#########hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh##############################################################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      '##########################################################hhhhhhhhhhhhhhhhhhhhhhhhhh#######hhhhhhhhhhhhhhhhhhhhhhhhhhhhh########################################################################hhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      '########################################################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh############################################################################hhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      '######################################################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh################################################################################hhhhhhhhhhhhhhhhhhhhhhhhhh',
      '#####################################################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh###################################################################################hhhhhhhhhhhhhhhhhhhhhhhhh',
      '###################################################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh######################################################################################hhhhhhhhhhhhhhhhhhhhhhhh',
      '############################################################################################################################################################################################################################',
    ],
  },
  {
    name: 'Mt. Shuksan',
    lat: 48.8311,
    lon: 121.6031,
    metres: 2783,
    feet: '9,131',
    look: 'north',
    grid: [
      '.........................................................................................................................................s',
      '.......................................................................................................................................sss',
      '.......................................................................................................................................msss',
      '......................................................................................................................................mmmss',
      '...................................................................................................................................mmmmmmsssss',
      '...................................................................................................................................mmmm**sssss',
      '..................................................................................................................................mmm*****ssssssssss',
      '..................................................................................................................................********ssssssssss',
      '.................................................................................................................................**********ssssssssss',
      '................................................................................................................***...........******************mmsssssssssss',
      '...............................................................................................................*****sss.....********************mmmsssssssssssss**',
      '.............................................................................................................*******ssssssss********************mmssssssssssss********ss................ss',
      '............................................................................................................*******sssssssssssss****************sssssssssssss**********sss**..**.ssss...sss.%%s....sss..m',
      '............................................................................................................*******sssssssssssssssssss*******sssssssssssssssss********************s**.***mmm%%sssssssmmmmmm.%.m',
      '..........................................................................................................**********sssssssssssssssssssss**sssssssssssssssssssss*************************mmmmmmsssmmmmmmmmmmm.m%%%....%%%',
      '..........................................................................................................*mmm*******ssssssssssssssssssssssssssssssssssssssssssss***********************mmmmmmmmmmmmmmmmmmmmmmm%%%%%%%%%%%%%',
      '........................................................................................................*mmmmm*******ssssssssssssssssssssssssssssssssssssssssssssss********************mmmmmmmmmmmmmmm***mmmmmmm%%%%%%%%%%%%',
      '.......................................................................................................mmmmmmm*******sssssssssssssssssssssssssssssssssssssssssssssss******************mmmmmmmmmmmmmmmm***mmmmmmmm%%%%%%%%%%%',
      '.......................................................................................................mmmmmmm***mm*ssssssssssssssssssssssssssssssssssssssssssssssss*****************mmmmmmm***mm**mmmm**mmmmmmmm%%%%%mm%%%%',
      '....................................................................................................**mmmmmmmmm*mmmmssssssssssssssssssssssssssssssssss*mmmsssss%sss*****************mmmmmmm*********mmmmssmmmmmmmm%%%%mm%%%%',
      '...................................................................................................**mmmmmmmmmmmmmm%%sssssssssssssssssss%%sssssssssss**mmmmsss%%%**************mmmmmmmmmmm***********mmmssmmmmmmmmm%%%mm%%%%',
      '...................................................................................................*mmmmmmmmmmmmmmmmmmsssssssssssssssss%%%%sssssssssss**mmmms%%%m*************mmmmmmmmmmm************mmmmmmmmmmmmmm%%%%%%%%%',
      '.................................................................................................**mmmmmmmmmmmmmmmmmmmmmmmsssssss%%%ss%%%%%sssssssssss**mmmmmmmmmm*****ssss***mmmmmmmmmmm***********mmmmm%%%mmmmmmmm%%%%%%%%',
      '.................................................................................................mmmmmmmmmmmmmmmmmmmmmmmmmmsssss%%%%%%%%%%%%sssssssssss%mmmmmmmmmmm***ssssss**mmmmmmmmmmmm**********mmmmm%%%%mmmmmmmm%%%%%%%',
      '...............................................................................................mmmmmmmmmmmmmmmmmmmmmmmmmmmmmssss%%%%%%%%%%%%sssssssssss%%mmmmmmmmmmmmmmssssssmmmmmmmmmmmmm**********mmmmm%%%%%mmmmmmmm%%%%%m',
      '.............................................................................................mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmss%%%%%%%%%%%%%sssssssssss%%%mmmmmmmmmmmmmmsssssmmmmmmmmmmmmmm*********mmmmm%%%%%mmmmmmmmm%%%mm',
      '.............................................................................................mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhhh%%%%%%%%%%%%%%ssssssssss%%%%mmmmmmmmmmmmmmssss%mmmmmmmmmmmmm********mmmmmm%%%%%%mmmmmmmmmmmmm',
      '...................................................................................%%..**mm.mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhhhh%%%%%%%%%%%%%%%%%%ssssss%%%%%mmmmmmmmmmmmmmmm%%%mmmmmmmmmmmmm*mmmmmmmmmmmm%%%%%%%mmmmmmmmmmmm',
      '................................................................................*.%%%%.*mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhhhhh#%%%%%%%%%%%%%%%%%%ssss%%%%%%%mmmmmmmmmmmmmmm%%%%mmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%%mmmmmmmmmmm',
      '...................................................+..........................mm**%%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhhhhh####%%%%%%%%%%%%%%%%%sss%%%%%%%%mmmmmmmmmmmmmm%%%%%mmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%%mmmmmmmmmmm',
      '...................................................++++......................mmmmm%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhhhhh#####%%%%%%%%%%%%%%%%%s%%%%%%%%%%mmmmmmmmmmmmmm%%%mmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%%mmmmmmmmmm',
      '.................................................===++++++++++..............mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhhhhhh#######%%%%%%%%%%%%%%%%%%%%%%%%%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%%%mmmmmmmmm',
      '.%%..............................................======+++++++=........mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhhhhhhh###########%%hhhh%%%%%%%%%%%%%%%%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%%%mmmmmmmm',
      '%%mm%%%.........................................========++++++==......mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhhhhhhhhh##########hhhhhhhhhhhh####%%%%%%%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%%%%%mmmmm',
      'mmmm%%%%...................=..................============+++===...=.mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhhhhhhhhhhh#####hhhhhhhhhhhhhhhhh######%%%%%%%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%%%%%mmm',
      'mmmm%%%%%%%.====.....=.=====%%%............========================mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhhhhhhhhhhhh####hhhhhhhhhhhhhhhhhhh######%%%%%%%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%%%%%%m',
      'mmmm%%%%%%%%=====m.======mm%%%%%===..===..==========mmm=======mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhhhhhhhhhhhhhhh##hhhhhhhhhhhhhhhhhhhh######%%%%%%%%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%%%%%%%',
      'mmmm%%%%%%%%%%%%%mmm==mmmmm%%%%%%==mm===mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh####hhh%%%%%hh%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%%%%%%',
      'mmmm%%%%%%%%%%%%%mmmmmmmmmmm%%%%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh###hhhh##%hhhh###mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%%%%%%',
      '############################################################################################################################################################################################################################',
    ],
  },
  {
    name: 'Mt. Olympus',
    lat: 47.8014,
    lon: 123.7111,
    metres: 2432,
    feet: '7,980',
    look: 'north',
    grid: [
      '.......................................................................................................................................mm.s......*',
      '......................................................................................................................................*mmmmmmmmmmmmm',
      '..................................................................................................................................**.**mmmmmmmmmmmmmm*****%%mm.*s',
      '...............................................................................................................................********mmmmmmmmmmmmmm*****%%mmm*ss',
      '..............................................................................................mmss............................********mmmmmmmmmmmmmmm*****%mmmmmsssss..........*%',
      '.............................................................................................mmmsssssssss..s.sss..............*******mmmmmmmmmmmmmsss****mmmmmmmmssssss....ss..**....................................h.hh',
      '.............................................................................................mmmmsssmmsssssssssmm%%%....ss.****mmm**mmmmmmmmmmmmmssss***mmmmmmmm#####ss####sss*##..m................................hhhhh##',
      '............................................................................................mmmmmmmmmmmssssss%mmmm%%%%%mmm*****mmmmmmmmmmmmmmmmmmmsss**hhmmmmhhh##################.mmmm.......s..................hhhhhhhhh##',
      '......................................................................%....................mmmmmmmmmmm##%smmmmmmmmmm%%%mmmm%%%%mmmmmmmmmmmmmmmmmmmm###hhhh#mhhhh######################hhhhh###hhhhhhhh..hhhhhhhhhhhhhhhhhhhh',
      '..........................................##....................mmmm%%%%%%......mmm%%..mmmmmmmmmhhhhh#####mmmmmmmmmmm%%#mmmm%%#####mmm%%%##mmmmmm######hhhhhhhh########hh############hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      '..........................................###.....mm%%........mmmmmmm%%%%%....##mm%%%%%mmmmmmmhhhhhhhh####mmmmm%%%mmmhh###mhhh########%%%###############hhhhhhh########hhhh#########hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      '............%..................##..######.#####...mm%%%.....m%%mmmmm##%%%%%%hh###%%%%%%mmmmmmhhhhhhhhhhhhhhhhhhh%%mmhhhh##hhhh############################hhhh##########hhh#########hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      '............%%%......h.....hhh###################mmm#%%%%%mmmmmmmmm####%%%%hhhh##h%%%hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh##############################hh###########################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      '.....mmm%.mmm%%%...hh####h.hh####hhh###################%%%%mmmmhhhh####hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh############################################################hhhh###hhhh###hhhhhhhhhhhhhhhhhhh##',
      '...hhmmm%%mmmm%%hhhh#####hhh####hhhhh###################%%%%mmhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh###############################################################hh#####hh#####hhhhhhhhhhhhhhhh####',
      'hhhhhhhhh%mmmhhhhhh##############hhhhh############hh#####hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh##############################################################hhhh###hh#######hhhhhhhhhhhhh######',
      'hhhhhhhhhhhhhhhhh###################h#############hhhh##hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh################################################################hhhhhhhhhhh########hhhhhhhhh#######',
      'hhhhhhhhhhhhhhhhh##################################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh################################################################hhhhhhhhhhh#########hhhhhhh########',
      'hhhhhhhhhhhhhhh######################################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh###################################################################hhhhhhhhhhh#########hhhhh#########',
      '####hhhhhhhh##########################################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh######################################################################hhhhhhhh#######################',
      '########hhh#############################################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh###########################################################################hhhh########################',
      '###########################################################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh#######################################################################################################',
      '############################################################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh#########################################################################################################',
      '##############################################################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh#########################################################################################################',
      '################################################################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh###########################################################################################################',
      '##################################################################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh###########################################################################################################',
      '###################################################################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh#############################################################################################################',
      '#####################################################################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh#############################################################################################################',
      '######################################################################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh###############################################################################################################',
      '########################################################################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh###############################################################################################################',
      '##########################################################################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh################################################################################################################',
      '############################################################################hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh#################################################################################################################',
      '#############################################################################hhhhhhhhhhhhhhhhhhhhhhhhhhhhh##################################################################################################################',
      '##############################################################################hhhhhhhhhhhhhhhhhhhhhhhhhhh###################################################################################################################',
      '###############################################################################hhhhhhhhhhhhhhhhhhhhhhhhh####################################################################################################################',
      '################################################################################hhhhhhhhhhhhhhhhhhhhhh######################################################################################################################',
      '##################################################################################hhhhhhhhhhhhhhhhhhh#######################################################################################################################',
      '####################################################################################hhhhhhhhhhhhhhh#########################################################################################################################',
      '######################################################################################hhhhhhhhhhh###########################################################################################################################',
      '############################################################################################################################################################################################################################',
    ],
  },
  {
    name: 'Mt. Stuart',
    lat: 47.4751,
    lon: 120.9026,
    metres: 2870,
    feet: '9,415',
    look: 'north',
    grid: [
      '.......................................................................................................................................***',
      '.......................................................................................................................................****s.s%%',
      '..................................................................................................................................%%%.m****ss*%%',
      '................................................................................................................................mm%%%%mmm******%%',
      '..............................................................................................................................mmmm%%%mmmmm******%',
      '.............................................................................................................................mmmmmmmmmmmmmm*****ss',
      '.............................................................................................................................mmmmmmmmmmmmmmm****sssss',
      '............................................................................................................................mmmmmmmmmmmmmmmmmmm*sssssss.......m',
      '............................................................................................................................mmmmmmmmmmmmmmmmmmmmsssssss......mmmm%%',
      '..........................................................................................................................*mmmmmmmmmmmmmmmmmmmmmm%%sssss%%...mmmmm%s..............................................%',
      '........................................................................................................................***mmmmmmmmmmmmmmmmmmmmmmm%%sssmmmmmmmmmmmmms.m.......................................mmmm%%%',
      '.......................................................................................................................**mmmmmmmmmmmmmmmmmmmmmmmmmmm%%%mmmmmmmmmmmmmmmmm....................................mmmmmm%%%%',
      '......................................................................................................................mmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%mmmmmmmmmmmmmmmmmmm%..............................%%mmmmmmm%%%%',
      '.....................................................................................................................mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%mmmmmmmmmmmmmmmmmm%%.....................%....%%%%%mmmmmmmm%%%',
      '....................................................................................................................mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%mmmmmmmmmmmmmmmmm%%%%%.................%%%.%%%%%%%mmmmmmmmm%%%%%%%',
      '......................................................m%.....%%.....................................................mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%mmmmmmmmmhhhmmmm%%%%%...............mm%%%%%%m%%mmmmmmmmmmmm%%%%%%',
      '............................................%........mm%%....%%%%..................................................mmmmmmmm##mmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%mmmmmmmhhhhhmmmmmm%%%........m.....mmm%%%%mmmmmmmmmmmmmmmmmm%%%%',
      '..........................................mmm%%%.%%mmmm%%%%%%%%%%%%............................................#.mmmmmmmmhh####mmmmmmmmmmmmmmmmmmmmmm%%%%%%%mmmmmmhhhhhh#mmmmmm%%%%.....m%%.%.mmmmm%%%mmmmmmmmmmmmmmmmmm%%%%',
      '........................................mmmmmm%%%%%%mm%%%%%%%%%%%%%%%........................................#####mmmmmhhhhh#####mmmmmmmmm#hh#mmmmm%%%%%%%%%mmmmmmhhhhhh###mmmmm%%%mm..mm%%%%%mmmmmm%%mmmmmmmmmmmmmmmmmm%%%%',
      '......................................mmmmmmmmm%%%%%%%%%%%%%%%%%%%%%%.................................hh#############hhhhhhhh####hhhhhhhhhhhhhhhhhhh%%%%%%%%%mmmmhhhhhhh####mmmmmmmmmmmmm%%%%%mmmmmm%%%mmmmmmmmmmmmmmmmmm%%%',
      '......................................mmmmmmmmmm%%%%%%%%%%%%%%%%%%%%%%%%........hhh....hh####hhh##...hhhhhhhhhhhh####hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh###%%%%%%mmmhhhhhhhh#####mmmmmmmmmmmmm%%%%mmmmmm%%%mmmmmmmmmmmmmmmmmmm%%',
      '.....................................mmmmmmmmmmmmmmm%%%%%%%%%%%%%%%%%%%%%.......hhhh.hhhhhhhhhhh###hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh############hhhhhhhhhh######mmmmmmmmmmmm%%mmmmmmmm%%%mmmmmmmmmmmmmmmmmmhh',
      '.%%.................................mmmmmmmmmmmmmmmmmm%%%%mmm%%%%%%%%%%%%%....hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh###############hhhhhhhhh##############mmmm%%mmmmmmmm%%%mmmmmmmmmmmmmmmmhhhh',
      '%%%%..................%.....h##%.mmmmmmmmmmmmmmmmmmmmmmmmmmmmm%%%%%%%%%%%%%.hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh#################hhhhhhhh###############mmm%%mmmmmmm%%%%mmmmmmmmmmmmmmhhhhh',
      '%%%%.####..###..%%%%%%%%...hhh##.mmmmmmmmmmmm%%mmmmmmmmmmmmmmmm%%%%%%%%%%mmhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh#########hhhhhh##hhhhhhhhh###h###########mm%%mmmmmmmm%%%mmmmmmmmmmmmhhhhhhh',
      '%%%hhh#########%%%%hhh%%%mhhhh###mmmmmmmmmmm%%%%mmmmmmmmmmmmmmmm%%%%%%mmmmmhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh#######hhhhhhhhhhhhhhhhhh#h#h#############%%mmmmmmmmm%%mmmmmmmmmmmhhhhhhhh',
      '%hhhhh##########%%hhhhhhhhhhhh####%%mmmmmmmm%%%%%mmmmmmmmmmmmmmm%%%%%mmmmmhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh######hhhhhhhhhhhhhhhhhh###################mmmmmmmmmmmmmmmmmmmmhhhhhhhhhh',
      'hhhhhh###########hhhhhhhhhhhhh####%%%mmmmmmm%%%%%%mmmmmmmmmmmmmmm%%%%mmmmhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh###hhhhhhhhhhhhhhhhhh###################mmmmmmmmmmmm##mmmhhhhhhhhhhhh',
      'hhhhhh##########hhhhhhhhhhhhhh####%%%%mmmmmm%%%%%%mmmmmmmmmmmmmmmm%%mmmmhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh####hhhhhhhhhhhhhhhh####################mmmmmmmhhhh##hhhhhhhhhhhhhhh',
      'hhhhhh#########hhhhhhhhhhhhhhh#####%%%mmmmmmm%%%%%mmmmmmmmmmmmmmmmmmmmmhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh#####hhhhhhhhhhhhhh#####################mmmmmhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhh########hhhhhhhhhhhhhhhh#####%%%%mmmmmmm%%%%mmmmmmmmmmmmmmmmmmmmhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh######hhhhhhhhhhhhhh#####################hhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhh#######hhhhhhhhhhhhhhhhh######%%%mmmmmmmm%%mmmmmmmmmmmmmmmmmmmmhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh#######hhhhhhhhhhhhh###################hhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhh######hhhhhhhhhhhhhhhhh#######%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmmhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh#######hhhhhhhhhhhh#################hhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhh#####hhhhhhhhhhhhhhhhhhh######%%%mmmmmmmmmmmmmmmmmmmmmmmmmmmhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh########hhhhhhhhhhh############hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhh####hhhhhhhhhhhhhhhhhhhh#######%%%mmmmmmmmmmmmmmmmmmmmmmmmmhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh#########hhhhhhhhhhh###########hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhh##hhhhhhhh##hhhhhhhhhhh########%%%mmmmmmmmmmmmmmmmmmmmmmmhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh#########hhhhhhhhhhh###########hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhhh####hhhhhhhhhh########%%%mmmmmmmmmmmmmmmmmmmmmmhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh########hhhhhhhhhhh############hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhh######hhhhhhhhh#########%%mmmmmmmmmmmmmmmmmmmmmhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh######hhhhhhhhhhhh#############hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhh#######hhhhhhhhh#########%%%mmmmmmmmmmmmmmmmmmmhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh###hhhhhhhhhhhhhh#############hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
      '############################################################################################################################################################################################################################',
    ],
  },
]
